sudo: required

language: php

php:
  - 7.0

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - phpunit
